# Naive Bayes
classification algorithm based on Bayes' Theorem of Probability and the assumption that features are conditionally independent given the class.

GaussianNB = Used when features are continuous numerical values. We calculate the mean for each outcome then calculate the probability of the input for each output scenario and choose the highest one.

MultinomialNB = Used when features represent counts or frequencies. eg: the number of words is calculated to detect spam mails.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [5]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [6]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [7]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [8]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [9]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [10]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [12]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [14]:
model.fit(X_train,y_train)

GaussianNB()

In [15]:
model.score(X_test,y_test)

0.753731343283582

In [16]:
X_test[0:10]

     Pclass        Age     Fare  female
841       2  16.000000  10.5000   False
864       2  24.000000  13.0000   False
406       3  51.000000   7.7500   False
149       2  42.000000  13.0000   False
791       2  16.000000  26.0000   False
85        3  33.000000  15.8500    True
295       1  29.699118  27.7208   False
92        1  46.000000  61.1750   False
472       2  33.000000  27.7500    True
868       3  29.699118   9.5000   False

In [17]:
y_test[0:10]

841    0
864    0
406    0
149    0
791    0
85     1
295    0
92     0
472    1
868    0
Name: Survived, dtype: int64

In [18]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [19]:
model.predict_proba(X_test[:10])

array([[0.91542159, 0.08457841],
       [0.92909605, 0.07090395],
       [0.96594744, 0.03405256],
       [0.9326193 , 0.0673807 ],
       [0.91204054, 0.08795946],
       [0.52764483, 0.47235517],
       [0.75739989, 0.24260011],
       [0.592704  , 0.407296  ],
       [0.3005066 , 0.6994934 ],
       [0.97158335, 0.02841665]])

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.792     , 0.776     , 0.76      , 0.83064516, 0.74193548])

In [21]:
df1 = pd.read_csv("data/spam.csv")
df1.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [22]:
df1.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [24]:
df1['spam']=df1['Category'].apply(lambda x: 1 if x=='spam' else 0)
df1.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [25]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(df1.Message,df1.spam)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X1_train_count = v.fit_transform(X1_train.values)
X1_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7496))

In [29]:
from sklearn.naive_bayes import MultinomialNB
model1 = MultinomialNB()
model1.fit(X1_train_count,y1_train)

MultinomialNB()

In [30]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model1.predict(emails_count)

array([0, 1])

In [31]:
X1_test_count = v.transform(X1_test)
model1.score(X1_test_count, y1_test)

0.9856424982053122

In [32]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

Pipeline - instead of doing it in two steps pipline makes it into one

In [34]:
clf.fit(X1_train, y1_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [35]:
clf.score(X1_test,y1_test)

0.9856424982053122

In [36]:
clf.predict(emails)

array([0, 1])